export  const createTable  = async (conectObj)=> {
    try{
        const result = await conectObj.query(
            `CREATE TABLE IF NOT EXISTS users(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(150) ,
            email VARCHAR(40) NOT NULL,
            age INTEGER,
            is_online BOOLEAN DEFAULT false);`
        );

        console.log("database is create with name-USERS");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const dropTable = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `DROP TABLE workers;`,
        );

        console.log("TABLE WORKERS IS DELETE");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const renameTable = async (conectObj) => {
    try{
        const result = await conectObj.query(
            "ALTER TABLE users RENAME TO workers;",
        );

        console.log("rename database  name-USERS>WORKERS");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const addColumnPhone = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers ADD COLUMN 
            phone VARCHAR(25);`,
        );

        console.log("column phone is add");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const dropColumnPhone = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers DROP COLUMN 
            phone;`,
        );

        console.log("column phone is delete");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const getStructureTableWorkers = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `SELECT 
            column_name,
            data_type,
            is_nullable,
            column_default
            FROM information_schema.columns
            WHERE table_name = 'workers'
            ORDER BY ordinal_position;`,
        );

        console.table(result.rows);
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
}

export const addConstraintToAge = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers
            ADD CONSTRAINT adult_age CHECK (age>=18);`,
        );

        console.log("Constraint add to AGE age>=18");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
}

export const editTypeSalary = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers
            ALTER COLUMN salary TYPE VARCHAR(100);`,
        );

        console.log("Salary type is NUMERIC>TEXT");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
}

export const editNameConstraintNotNull = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers
            ALTER COLUMN name SET NOT NULL;`,
        );

        console.log("Name constraint  is_nullable-NO");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
}

export const dropConstraintToEmail = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `ALTER TABLE workers
            ALTER COLUMN email DROP NOT NULL;`,
        );

        console.log("Drop constraint to email");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
}

export  const createTableSalaryInfo  = async (conectObj)=> {
    try{
        const result = await conectObj.query(
            `CREATE TABLE IF NOT EXISTS salary_info(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            worker_id INTEGER NOT NULL,
            day_work SMALLINT DEFAULT 0,
            day_Off SMALLINT DEFAULT 0 ,
            day_salary INTEGER DEFAULT 0,
            bonus INTEGER DEFAULT 0,

            CONSTRAINT salary_info_worker_fk
            FOREIGN KEY (worker_id)
            REFERENCES workers(id)
            )`
        );

        console.log("database is create with name-SALARY_INFO");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}

export const dropTableSalaryInfo = async (conectObj) => {
    try{
        const result = await conectObj.query(
            `DROP TABLE salary_info;`,
        );

        console.log("TABLE SALARY_INFO IS DELETE");
        

    }catch (error){
        console.error(error);
    }finally {
       
        
    }
    
}